### ISSUE TITLE
Shrug reason not showing OK

### ISSUE THREAD

**Issue by nahueloyha** [baires/shouldideploy#17]
Hi! 

Issue: the shrug reason (¯\_(ツ)_/¯) is not showing OK, i see it like **¯_(ツ)_/¯** instead of **¯\_(ツ)_/¯**

Posible solution: maybe you need to escape the backslash with another backslash in reasons.js file? 

Platform: Chrome on Mac.

Thanks!

**Comment by baires** [comment]
Will take a look
