### ISSUE TITLE
Timezone inference is not working for me

### ISSUE THREAD

**Issue by vhoyer** [baires/shouldideploy#418]
The current method of infering the timezone (through moment) is not working for me :/ why don't we use the "new" `Intl.DateTimeFormat().resolvedOptions().timeZone` API to get the user time zone? this works fine for me, [it has great compatibility](https://caniuse.com/?search=Intl.DateTimeFormat().resolvedOptions().timeZone), and if this isn't enough, we can always use moment as a fallback :D or vise versa, use this API as a fallback for moment.

**Comment by HarshaVardhanNakkina** [comment]
@vhoyer where is this problem exactly? I want to contribute

**Comment by HarshaVardhanNakkina** [comment]
@baires where is the problem? can I do this?

**Comment by baires** [comment]
@HarshaVardhanNakkina this was implemented on #491
