### ISSUE TITLE
Deploys on dec-23?! Are you serious?

### ISSUE THREAD

**Issue by nallegrotti** [baires/shouldideploy#594]
C'mon guys we need a special list of reasons for Xmas eve & new year

**Comment by javiercanillas** [comment]
👍

**Comment by nallegrotti** [comment]
obviously I don't expect this to be deployed today ...

**Comment by javiercanillas** [comment]
I think the fix should be around here: https://github.com/baires/shouldideploy/blob/master/helpers/constans.js#L15

**Comment by cmdelatorre** [comment]
> obviously I don't expect this to be deployed today ...

Nor today 😜
