### ISSUE TITLE
Migrate to TypeScript

### ISSUE THREAD

**Issue by baires** [baires/shouldideploy#718]
Its is time. It should be kinda simple

**Comment by dennissiq** [comment]
@Ronkiro, @baires WDYT create a project (in the project label) to migrate to typescript? I would like help with this feature 😄

**Comment by baires** [comment]
Yupe, sounds like a plan, and incremental feature update sounds good. BTW there is a `typescript` tag

**Comment by dennissiq** [comment]
@baires I've created some tasks in the project, feel free to change, add or delete some tasks!

**Comment by dennissiq** [comment]
created in #833
